site_name: NGW's weblog
site_url: https://ngwork0301.github.io
site_author: NGW
# copyright: 'Copyright © 2021 NGW.'

theme:
  name: material
  language: ja
  features:
    tabs: true
  palette:
    accent: Black
    primary: Black
  extra:
    search:
        language: 'ja'
  icon:
    logo: material/school
    repo: fontawesome/brands/git-alt

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fereria
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fereria
    - icon: fontawesome/solid/bookmark
      link: https://zenn.dev/remiria

markdown_extensions:
    - meta
    - admonition
    - pymdownx.magiclink
    - fontawesome_markdown
    - def_list
    - mdx_math:
        enable_dollar_delimiter: true
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.smartsymbols
    - pymdownx.keys
    - pymdownx.highlight:
        linenums: true
        use_pygments: true
        noclasses: true
        pygments_style: monokai


extra_css:
    - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
    

extra:
    font:
        text: "Noto Sans JP"
        code: "Consolas"
extra_css:

extra_javascript: 
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

google_analytics:
  - 'UA-197500322-1'
  - 'auto'

plugins:
    - redirects:
        redirect_maps:
            'index.md': '2021/python-debug-gdb.md'

