site_name: NGW's weblog
site_url: https://ngwork0301.github.io
site_author: NGW
site_description: このサイトはNGWのブログです。このブログで述べられている内容はすべて私の個人的な意見に基づくものです。誤記やご意見等はGithub issueまたはtwitterへご連絡ください。
# copyright: 'Copyright © 2021 NGW.'

theme:
  name: material
  language: 'ja'
  features:
    tabs: true
  palette:
    accent: Black
    primary: Black
  custom_dir: overrides
  features:
    - search.suggest
  extra:
    search:
        language: 'ja'

markdown_extensions:
    - meta
    - admonition
    - fontawesome_markdown
    - footnotes
    - def_list
    - mdx_math:
        enable_dollar_delimiter: true
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.magiclink
    - pymdownx.highlight:
        linenums: true
        use_pygments: true
        noclasses: true
        pygments_style: monokai
    - mdx_truly_sane_lists:
        nested_indent: 2

extra:
    font:
        text: "Noto Sans JP"
        code: "Consolas"
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/ngwork0301
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/ngwork0301
      - icon: fontawesome/solid/bookmark
        link: https://zenn.dev/ngw
      - icon: fontawesome/solid/rss
        link: https://ngwork0301.github.io/feed_rss_created.xml

extra_css:
    - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
    - "css/custom.css"

extra_javascript: 
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

google_analytics:
  - 'UA-197500322-1'
  - 'auto'

plugins:
    - search:
        lang:
          - ja
        prebuild_index: true
    - git-revision-date-localized:
        type: 
          iso_datetime
    - redirects:
        redirect_maps:
            'index.md': '2022/jobs_to_be_Done_jobs_theory.md'
    - rss
    - git-revision-date-localized
